name: sagrado_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^0.11.0
  flutter_masked_text: ^0.8.0
  flutter_keychain: ^1.0.0
  http: ^0.12.0+2
  intl: ^0.15.8
  shared_preferences: ^0.5.3+1
  provider: ^3.0.0+1
  dio: ^2.1.13
  carousel_pro: ^1.0.0
  flutter_cupertino_settings: ^0.1.0
  font_awesome_flutter: ^8.5.0
  flutter_facebook_login: ^2.0.1
  flutter_vk_login: ^0.0.2
  url_launcher: ^5.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/sagrado-logo.png
    - assets/images/logo.png
    - assets/images/loginScreen.png
    - assets/images/checkLogin.png
    - assets/images/uncheckLogin.png
    - assets/images/check-inactive.png
    - assets/images/check-active.png
    - assets/images/arrow.png
    - assets/images/small-arrow.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Circe
      fonts:
        - asset: assets/fonts/Circe-Regular.ttf
        - asset: assets/fonts/Circe-Bold.ttf
          weight: 700
        - asset: assets/fonts/Circe-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Circe-ExtraLight.ttf
          weight: 200
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
